### ISSUE TITLE
No way to set the command you want to run without recompiling

### ISSUE THREAD

**Issue by guysoft** [jonasc/command-notification#1]
Hey,
First of all - cool! 
Seeing code I wrote just under 7 years ago still being used is awesome.
My first github repo was only put in Dec 2010, so a month after I wrote the code.

Just thought I'd note that if anyone wants to use this, you will need to edit the command line: https://github.com/jonasc/command-notification/blob/master/command-notification.c#L167
Which has no way of setting it without com compiling everything again.
(I'm not really using this anymore, so I am not going to do it, but thought its good to have this as an issue here at least)

**Comment by jonasc** [comment]
You are completely right. I will leave this open and might have a look on how one can add a very simple configuration interface.

My main motivation was to be able to run a second command once all notifications are disabled, so just a quick and dirty fix ;-).

**Comment by jonasc** [comment]
So I just looked at the plugin again (I was just using it in the background for some time now) and it *has* a configuration screen where you can change the program being run, see attached picture.
The two binaries I have in the code are then just the default values.

![test](https://cloud.githubusercontent.com/assets/2046766/23017002/d75eed76-f438-11e6-96ff-26a4fc28d23c.png)

**Comment by guysoft** [comment]
Oh, I guess I forgot about that.
